Name: Merlin Varsha W
Project: SpendDNA
Dataset: DADS MP2 Dataset
Tools:Python,NumPy,Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving DADS MP2 Dataset.csv to DADS MP2 Dataset.csv

In [ ]:
df = pd.read_csv("DADS MP2 Dataset.csv")

In [ ]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [ ]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1328
Columns: 8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB

In [ ]:
df.head(10)

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962
5,2024-01-01,14:48,BHIM ZEPTO,DR,Rs. 625,677650.0,UPI,TXN370902
6,2024-01-01,14:50,UPI-UBER-2426@HDFCBANK,Debit,Rs. 148,677020.0,UPI,TXN546173
7,01-Jan-24,21:44,BHIM-BLINKIT,Debit,₹482,677168.0,UPI,TXN599219
8,2024-01-02,05:18,POS SWIGGY BANGALORE,Debit,Rs. 537,676177.0,UPI,TXN293319
9,02/01/24,06:55,UPI-GROWWPAY@HDFCBANK,DR,3956,672221.0,UPI,TXN418594

Transactio Parser

In [ ]:
df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [ ]:
print("Original Data Types:")
print(df.dtypes)

Original Data Types:
Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

In [ ]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

In [ ]:
df['date'] = pd.to_datetime(
    df['Date'],
    errors='coerce',
    dayfirst=True
)

In [ ]:
print("Unparseable dates:", df['date'].isna().sum())

Unparseable dates: 1184

In [ ]:
print(df[['Date', 'date']].head(10))

          Date       date
0   2024-01-01 2024-01-01
1    01-Jan-24        NaT
2    01-Jan-24        NaT
3   2024-01-01 2024-01-01
4  01 Jan 2024        NaT
5   2024-01-01 2024-01-01
6   2024-01-01 2024-01-01
7    01-Jan-24        NaT
8   2024-01-02 2024-02-01
9     02/01/24        NaT

In [ ]:
df['amount'] = (
    df['Amount']
    .astype(str)
    .str.replace('₹', '', regex=False)
    .str.replace('Rs.', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

In [ ]:
print("Unparseable amounts:", df['amount'].isna().sum())

Unparseable amounts: 0

In [ ]:
print(df[['Amount', 'amount']].head(10))

    Amount   amount
0    ₹2462   2462.0
1    50.00     50.0
2   ₹84728  84728.0
3    ₹1828   1828.0
4   270.00    270.0
5  Rs. 625    625.0
6  Rs. 148    148.0
7     ₹482    482.0
8  Rs. 537    537.0
9     3956   3956.0

In [ ]:
df['type'] = df['Type'].astype(str).str.lower().str.strip()

df['type'] = df['type'].replace({
    'dr': 'debit',
    'debit': 'debit',
    'cr': 'credit',
    'credit': 'credit'
})

In [ ]:
print(df['type'].value_counts())

type
debit     1322
credit       6
Name: count, dtype: int64

In [ ]:
print("Rows before removing duplicates:", len(df))

Rows before removing duplicates: 1328

In [ ]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 18

In [ ]:
df = df.drop_duplicates().copy()

In [ ]:
print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 1310

In [ ]:
print("=" * 50)
print("TRANSACTION PARSER CHECK")
print("=" * 50)

print("Original rows       :", 1328)
print("Duplicates removed  :", duplicates)
print("Clean rows           :", len(df))
print("Unparseable dates    :", df['date'].isna().sum())
print("Unparseable amounts  :", df['amount'].isna().sum())
print("Transaction types    :", df['type'].unique())

==================================================
TRANSACTION PARSER CHECK
==================================================
Original rows       : 1328
Duplicates removed  : 18
Clean rows           : 1310
Unparseable dates    : 1167
Unparseable amounts  : 0
Transaction types    : ['debit' 'credit']

2.VENDOR EXTRACTOR

In [ ]:
descriptions = df['Description'].unique()

print("Number of unique descriptions:", len(descriptions))

for description in descriptions:
    print(description)

Number of unique descriptions: 283
AMAZON SELLER SVCS
BHIM-BMTC
NEFT-TECHCRUSH LABS-SALARY MAY24
UPI-AMAN-8934@OKAXIS
BHIM-BLINKIT
BHIM ZEPTO
UPI-UBER-2426@HDFCBANK
POS SWIGGY BANGALORE
UPI-GROWWPAY@HDFCBANK
OLA ELECTRIC
BMS MOVIE TICKETS
POS OLA-PRIME
SWIGGY-INSTAMART
UPI-STARBUCKS@AXIS
UPI-THIRDWAVE@OKAXIS
ANI Technologies
BMTC BUS PASS
POS TRUFFLES
FLIPKART INDIA
POS SWIGGY-RESTAURANT
GROFERS INDIA P L
POS UBER BANGALORE
BANGALORE ELEC SUPPLY
TWC INDIA
UPI-BESCOM-BILL@HDFCBANK
UPI-AMAN-0816@OKAXIS
ROPPEN TRANSPORTATION
OLA CABS
POS ZOMATO
UPI-AMAZONPAY@HDFCBANK
POS BLINKIT
IMPS-RENT-LANDLORD-75500265
ZOMATO MEDIA P L
UPI-ANKIT-6430@OKAXIS
UPI-OLACABS@HDFCBANK
UPI-JIORECHARGE@PAYTM
UPI-CCD@HDFCBANK
Swiggy*Order
INSTAMART BANGALORE
UPI-ZOMATO-LIMITED@PAYTM
AVENUE SUPERMARTS
POS HP PETROL STATION
UPI-VIKAS-6060@OKAXIS
POS BANGALORE RESTAURANT
UPI-ZERODHA-COIN@AXIS
BHIM SWIGGY
UPI-BOOKMYSHOW@HDFCBANK
BLINKIT BANGALORE
POS ZEPTO BANGALORE
UPI-DMART@OKAXIS
UPI-RAPIDO@OKAXIS
BUNDL Tech P L
TATA STARBUCKS
POS CAFE COFFEE DAY
UBER SYSTEMS INDIA
UPI-MYNTRA@HDFCBANK
UPI-FLIPKART@HDFCBANK
UPI-BWSSB@AXIS
UPI-ZOMATO6393@OKICICI
AMAZON IN
UPI-NETFLIX-MEMB@HDFCBANK
AIRTEL POSTPAID
Amazon Pay India
UPI-PRIYA-2221@OKAXIS
POS FLIPKART BANGALORE
POS NYKAA BANGALORE
VI POSTPAID
UPI-UBER-6457@HDFCBANK
POS BPCL PETROL PUMP
TUMMOC-BMTC
POS INDIAN OIL BANGALORE
UPI-SPOTIFY-IN@AXIS
POS DINEOUT
UPI-BLINKIT-0656@PAYTM
UPI-SWIGGY5057@OKAXIS
ZOMATO-DINING
COFFEE DAY GLOBAL
UPI-NYKAA@AXIS
UPI-SWIGGY9672@OKAXIS
RAPIDO BIKE TAXI
UPI-SWIGGY-6560@HDFCBANK
DISNEY HOTSTAR
NEFT ZERODHA BROKING
UBER INDIA
AMAZONIN MARKETPLACE
UPI-ZOMATO4674@OKICICI
POS EMPIRE RESTAURANT
ATM-WDL-SBI-5715
UPI-SWIGGY-9474@HDFCBANK
POS MEGHANA FOODS
ZEPTO MARKETPLACE
UPI-IOC9075@HDFCBANK
UPI-SWIGGY-2954@HDFCBANK
FKART INTRNET
UPI-SWIGGY-5808@HDFCBANK
UPI-BIGBASKET@HDFCBANK
AMZN-INTPYMT
AMZN PRIME
MYNTRA-ORDER
UPI-SWIGGY-5551@HDFCBANK
BUNDL TECH-INSTAMART
MYNTRA DESIGNS
POS MYNTRA
POS DMART BANGALORE
BIGBASKET BANGALORE
POS THIRD WAVE COFFEE
SPOTIFY INDIA
UPI-SWIGGY-7959@HDFCBANK
UPI-BLINKIT-3798@PAYTM
UPI-BLINKIT-3397@PAYTM
UPI-SWIGGY-INSTAMART@OKAXIS
ZOMATO BENGALURU
BESCOM ELEC BILL
IMPS-RENT-LANDLORD-39598076
UPI-RESTAURANT-7285@PAYTM
POS STARBUCKS BANGALORE
UPI-SWIGGY2461@OKAXIS
UPI-SWIGGY4619@OKAXIS
IMPS ZERODHA-COIN
UPI-SWIGGY3675@OKAXIS
RELIANCE JIO
UPI-SWIGGY-1309@HDFCBANK
NETFLIX ENTERTAINMENT
UPI-UBER-5667@HDFCBANK
FSN E-COMMERCE
UPI-BLINKIT-2630@PAYTM
UPI-RESTAURANT-7678@PAYTM
ATM-WDL-HDFC-4942
Uber*Trip
UPI-SWIGGY1616@OKAXIS
UPI-NEHA-9795@OKAXIS
BIGTREE ENTERTAINMENT
UPI-ZOMATO4177@OKICICI
INNOVATIVE RETAIL
POS INSTAMART
UPI-RESTAURANT-3715@PAYTM
UPI-UBER-1232@HDFCBANK
STAR INDIA PVT LTD
UPI-SWIGGY-5933@HDFCBANK
UPI-RESTAURANT-0251@PAYTM
UPI-ZOMATO3977@OKICICI
UPI-BLINKIT-7138@PAYTM
UPI-SWIGGY8086@OKAXIS
UPI-SWIGGY-6605@HDFCBANK
AMAZON PRIME VIDEO
UPI-SWIGGY-7844@HDFCBANK
UPI-SWIGGY-1487@HDFCBANK
UPI-UBER-6248@HDFCBANK
UPI-NEHA-5906@OKAXIS
KIRANAKART TECH
UPI-SWIGGY-7642@HDFCBANK
UPI-ZEPTO-4547@HDFCBANK
UPI-ZEPTO-4563@HDFCBANK
IMPS-RENT-LANDLORD-51148088
UPI-RESTAURANT-6377@PAYTM
UPI-ZEPTO-3309@HDFCBANK
UPI-ZEPTO-0070@HDFCBANK
UPI-SWIGGY-8169@HDFCBANK
UPI-VIKAS-5416@OKAXIS
UPI-HOTSTAR@AXIS
ATM-WDL-HDFC-9140
UPI-ZOMATO6436@OKICICI
ATM-WDL-SBI-4080
NETFLIX.COM
UPI-IOC0494@HDFCBANK
UPI-RESTAURANT-4630@PAYTM
UPI-IOC1246@HDFCBANK
Flipkart Internet
UPI-SWIGGY1600@OKAXIS
UPI-SWIGGY8576@OKAXIS
ATM-WDL-HDFC-8030
SPOTIFY*PREMIUM
UPI-BLINKIT-6907@PAYTM
BWSSB WATER BILL
UPI-RESTAURANT-7888@PAYTM
GROWW INVEST TECH
UPI-IOC2000@HDFCBANK
UPI-SWIGGY5466@OKAXIS
UPI-SNEHA-0942@OKAXIS
UPI-SWIGGY-2664@HDFCBANK
JIOFIBER
BHARTI AIRTEL LTD
UPI-UBER-0377@HDFCBANK
UPI-UBER-5112@HDFCBANK
UPI-ZOMATO1274@OKICICI
UPI-SWIGGY4144@OKAXIS
UPI-VI-RECHARGE@HDFCBANK
UPI-KARAN-5789@OKAXIS
UPI-BLINKIT-1501@PAYTM
ZERODHA-MF SIP
UPI-SWIGGY-9575@HDFCBANK
UPI-RESTAURANT-0753@PAYTM
NEXTBILLION-GROWW
UPI-ZOMATO5010@OKICICI
UPI-BLINKIT-1469@PAYTM
UPI-SWIGGY9328@OKAXIS
NYKAA E-RETAIL
ATM-WDL-HDFC-3609
UPI-SWIGGY0226@OKAXIS
UPI-SWIGGY9600@OKAXIS
IMPS-RENT-LANDLORD-36852906
UPI-ZOMATO7344@OKICICI
UPI-ZEPTO-9191@HDFCBANK
UPI-ZOMATO9481@OKICICI
UPI-IOC2115@HDFCBANK
UPI-SWIGGY-3513@HDFCBANK
UPI-RESTAURANT-3549@PAYTM
UPI-PRIYA-8750@OKAXIS
UPI-ZOMATO5845@OKICICI
UPI-ZEPTO-6004@HDFCBANK
UPI-BLINKIT-3223@PAYTM
UPI-SWIGGY1998@OKAXIS
ATM-WDL-ICICI-6478
UPI-SWIGGY0250@OKAXIS
UPI-RESTAURANT-5630@PAYTM
UPI-SWIGGY0894@OKAXIS
UPI-ANKIT-9877@OKAXIS
UPI-SWIGGY6412@OKAXIS
UPI-SWIGGY-1791@HDFCBANK
UPI-SWIGGY5867@OKAXIS
UPI-UBER-8525@HDFCBANK
UPI-SWIGGY-4758@HDFCBANK
UPI-BLINKIT-1165@PAYTM
UPI-SWIGGY4389@OKAXIS
ATM-WDL-SBI-0237
IMPS-RENT-LANDLORD-49966195
UPI-SWIGGY8720@OKAXIS
UPI-PRIYA-0104@OKAXIS
UPI-RESTAURANT-8932@PAYTM
UPI-SWIGGY9756@OKAXIS
UPI-SWIGGY-1714@HDFCBANK
VODAFONE IDEA LTD
ATM-WDL-SBI-0279
UPI-SWIGGY-6024@HDFCBANK
UPI-ZEPTO-2913@HDFCBANK
UPI-ZOMATO5406@OKICICI
UPI-RESTAURANT-3964@PAYTM
UPI-SWIGGY5737@OKAXIS
ATM-WDL-HDFC-8253
ZERODHA SECURITIES
UPI-AMAZON-PRIME@HDFCBANK
UPI-UBER-4781@HDFCBANK
UPI-RESTAURANT-5691@PAYTM
UPI-SWIGGY2847@OKAXIS
UPI-ZOMATO9682@OKICICI
UPI-IOC5182@HDFCBANK
UPI-ANKIT-5946@OKAXIS
UPI-SWIGGY9088@OKAXIS
UPI-UBER-1392@HDFCBANK
UPI-SWIGGY9983@OKAXIS
UPI-ZEPTO-1050@HDFCBANK
UPI-ANKIT-1837@OKAXIS
IMPS-RENT-LANDLORD-35126704
UPI-SWIGGY8392@OKAXIS
UPI-ZOMATO5117@OKICICI
UPI-ZOMATO4622@OKICICI
UPI-SWIGGY1418@OKAXIS
ATM-WDL-ICICI-9135
UPI-RESTAURANT-5531@PAYTM
UPI-ANKIT-6092@OKAXIS
UPI-SWIGGY7538@OKAXIS
ATM-WDL-ICICI-4172
UPI-ZEPTO-5207@HDFCBANK
ATM-WDL-SBI-4084
UPI-ZEPTO-7106@HDFCBANK
ATM-WDL-ICICI-4739
UPI-SWIGGY6053@OKAXIS
UPI-SWIGGY-3505@HDFCBANK
UPI-SWIGGY-0015@HDFCBANK
UPI-RESTAURANT-2648@PAYTM
ATM-WDL-SBI-0874
UPI-VIKAS-1878@OKAXIS
UPI-SWIGGY6013@OKAXIS
UPI-SWIGGY-8838@HDFCBANK
UPI-VIKAS-9964@OKAXIS
UPI-RESTAURANT-7645@PAYTM
ATM-WDL-ICICI-3918
UPI-SWIGGY-9077@HDFCBANK
UPI-RESTAURANT-0874@PAYTM
ATM-WDL-ICICI-5025
UPI-SWIGGY3466@OKAXIS
UPI-BLINKIT-1828@PAYTM
UPI-UBER-3218@HDFCBANK

In [ ]:
vendor_keywords = {

    # Food Delivery / Quick Commerce
    'Swiggy': ['SWIGGY', 'BUNDL', 'INSTAMART'],
    'Zomato': ['ZOMATO'],

    'Blinkit': ['BLINKIT', 'GROFERS'],
    'Zepto': ['ZEPTO', 'KIRANAKART TECH'],

    # E-commerce
    'Amazon': ['AMAZON', 'AMZN'],
    'Flipkart': ['FLIPKART', 'FKART'],
    'Myntra': ['MYNTRA'],
    'Nykaa': ['NYKAA', 'FSN E-COMMERCE'],

    # Transport
    'Uber': ['UBER'],
    'Ola': ['OLA', 'ANI TECHNOLOGIES'],
    'Rapido': ['RAPIDO', 'ROPPEN TRANSPORTATION'],

    # Investments
    'Zerodha': ['ZERODHA'],
    'Groww': ['GROWW', 'NEXTBILLION'],

    # Entertainment
    'BookMyShow': ['BOOKMYSHOW', 'BMS MOVIE TICKETS',
                   'BIGTREE ENTERTAINMENT'],
    'Netflix': ['NETFLIX'],
    'Spotify': ['SPOTIFY'],
    'Disney+ Hotstar': ['DISNEY HOTSTAR', 'STAR INDIA PVT LTD'],

    # Restaurants / Cafes
    'Truffles': ['TRUFFLES'],
    'Starbucks': ['STARBUCKS'],
    'Cafe Coffee Day': ['COFFEE DAY'],
    'Third Wave Coffee': ['THIRDWAVE', 'THIRD WAVE COFFEE', 'TWC INDIA'],
    'Restaurants': ['RESTAURANT', 'DINEOUT', 'EMPIRE RESTAURANT',
                    'MEGHANA FOODS'],

    # Grocery / Supermarkets
    'BigBasket': ['BIGBASKET', 'INNOVATIVE RETAIL'],
    'DMart': ['AVENUE SUPERMARTS', 'DMART'],

    # Transport / Fuel
    'BMTC': ['BMTC', 'TUMMOC'],
    'HP Petrol': ['HP PETROL'],
    'BPCL Petrol': ['BPCL'],
    'Indian Oil': ['INDIAN OIL', 'IOC'],

    # Telecom / Utilities
    'Airtel': ['AIRTEL', 'BHARTI AIRTEL'],
    'Jio': ['JIO', 'RELIANCE JIO'],
    'VI Postpaid': ['VI POSTPAID', 'VODAFONE IDEA', 'VI-RECHARGE'],
    'BESCOM': ['BESCOM', 'BANGALORE ELEC SUPPLY'],
    'BWSSB': ['BWSSB'],

    # Salary / Rent
    'Salary': ['TECHCRUSH LABS', 'SALARY'],
    'Rent': ['RENT-LANDLORD', 'LANDLORD'],

}

In [ ]:
def extract_vendor(description):
    description = str(description).upper().strip()

    # ATM withdrawals
    if 'ATM-WDL' in description:
        return 'Cash Withdrawal'

    # Check known vendors first
    for vendor, keywords in vendor_keywords.items():
        for keyword in keywords:
            if keyword in description:
                return vendor

    # P2P transfers
    if description.startswith('UPI-') and '@' in description:
        return 'P2P Transfer'

    return 'Uncategorised'

In [ ]:
df['vendor_clean'] = df['Description'].apply(extract_vendor)

In [ ]:
df[['Description', 'vendor_clean']].head(20)

                         Description       vendor_clean
0                 AMAZON SELLER SVCS             Amazon
1                          BHIM-BMTC               BMTC
2   NEFT-TECHCRUSH LABS-SALARY MAY24             Salary
3               UPI-AMAN-8934@OKAXIS       P2P Transfer
4                       BHIM-BLINKIT            Blinkit
5                         BHIM ZEPTO              Zepto
6             UPI-UBER-2426@HDFCBANK               Uber
7                       BHIM-BLINKIT            Blinkit
8               POS SWIGGY BANGALORE             Swiggy
9              UPI-GROWWPAY@HDFCBANK              Groww
10                      OLA ELECTRIC                Ola
11                 BMS MOVIE TICKETS         BookMyShow
12                     POS OLA-PRIME                Ola
13                  SWIGGY-INSTAMART             Swiggy
14                UPI-STARBUCKS@AXIS          Starbucks
15              UPI-THIRDWAVE@OKAXIS  Third Wave Coffee
16                  ANI Technologies                Ola
17                     BMTC BUS PASS               BMTC
18                      POS TRUFFLES           Truffles
19                    FLIPKART INDIA           Flipkart

In [ ]:
print(df['vendor_clean'].value_counts())

vendor_clean
Swiggy               243
Zomato               121
Ola                   87
Amazon                86
Uber                  71
Zepto                 71
Restaurants           64
Rapido                55
Blinkit               55
Flipkart              47
Starbucks             42
BMTC                  37
P2P Transfer          31
Third Wave Coffee     31
DMart                 22
Myntra                20
Nykaa                 19
BigBasket             19
Cafe Coffee Day       17
Cash Withdrawal       17
Indian Oil            17
BESCOM                15
Zerodha               14
BookMyShow            13
Netflix               10
HP Petrol              9
Disney+ Hotstar        9
Truffles               9
Groww                  9
Spotify                8
VI Postpaid            8
BWSSB                  8
Salary                 6
Jio                    6
Rent                   6
Airtel                 6
BPCL Petrol            2
Name: count, dtype: int64

In [ ]:
print("Uncategorised:",
      (df['vendor_clean'] == 'Uncategorised').sum())

Uncategorised: 0

In [ ]:
df['vendor_clean'].value_counts()

vendor_clean
Swiggy               243
Zomato               121
Ola                   87
Amazon                86
Uber                  71
Zepto                 71
Restaurants           64
Rapido                55
Blinkit               55
Flipkart              47
Starbucks             42
BMTC                  37
P2P Transfer          31
Third Wave Coffee     31
DMart                 22
Myntra                20
Nykaa                 19
BigBasket             19
Cafe Coffee Day       17
Cash Withdrawal       17
Indian Oil            17
BESCOM                15
Zerodha               14
BookMyShow            13
Netflix               10
HP Petrol              9
Disney+ Hotstar        9
Truffles               9
Groww                  9
Spotify                8
VI Postpaid            8
BWSSB                  8
Salary                 6
Jio                    6
Rent                   6
Airtel                 6
BPCL Petrol            2
Name: count, dtype: int64

In [ ]:
uncategorised = df[df['vendor_clean'] == 'Uncategorised']

print("Remaining uncategorised descriptions:")
print(uncategorised['Description'].drop_duplicates().to_string(index=False))

Remaining uncategorised descriptions:
Series([], )

In [ ]:
uncategorised = df[df['vendor_clean'] == 'Uncategorised']

print("Uncategorised transactions:", len(uncategorised))
print("\nUnique uncategorised descriptions:\n")

print(
    uncategorised['Description']
    .drop_duplicates()
    .to_string(index=False)
)

Uncategorised transactions: 0

Unique uncategorised descriptions:

Series([], )

In [ ]:
print("Total transactions:", len(df))
print("Unique vendors:", df['vendor_clean'].nunique())
print("Uncategorised:", (df['vendor_clean'] == 'Uncategorised').sum())

Total transactions: 1310
Unique vendors: 37
Uncategorised: 0

In [ ]:
uncategorised = df[df['vendor_clean'] == 'Uncategorised']

print(uncategorised[['Description']].to_string(index=False))

Empty DataFrame
Columns: [Description]
Index: []

3.CATEGORY TAGGER+ SPENDING OVERVIEW

In [ ]:
category_map = {

    # Food Delivery
    'Swiggy': 'Food Delivery',
    'Zomato': 'Food Delivery',

    # Quick Commerce
    'Blinkit': 'Quick Commerce',
    'Zepto': 'Quick Commerce',

    # E-commerce
    'Amazon': 'E-commerce',
    'Flipkart': 'E-commerce',
    'Myntra': 'E-commerce',
    'Nykaa': 'E-commerce',

    # Transport
    'Uber': 'Transport',
    'Ola': 'Transport',
    'Rapido': 'Transport',
    'BMTC': 'Transport',

    # Cafe
    'Starbucks': 'Cafe',
    'Cafe Coffee Day': 'Cafe',
    'Third Wave Coffee': 'Cafe',
    'Truffles': 'Cafe',

    # Restaurants
    'Restaurants': 'Restaurants',

    # Subscriptions
    'Netflix': 'Subscriptions',
    'Spotify': 'Subscriptions',
    'Disney+ Hotstar': 'Subscriptions',

    # Utilities
    'Airtel': 'Utilities',
    'Jio': 'Utilities',
    'VI Postpaid': 'Utilities',
    'BESCOM': 'Utilities',
    'BWSSB': 'Utilities',

    # Groceries
    'BigBasket': 'Groceries',
    'DMart': 'Groceries',

    # Investments
    'Zerodha': 'Investments',
    'Groww': 'Investments',

    # Fuel
    'HP Petrol': 'Fuel',
    'BPCL Petrol': 'Fuel',
    'Indian Oil': 'Fuel',

    # Entertainment
    'BookMyShow': 'Entertainment',

    # Personal Transfer
    'P2P Transfer': 'Personal Transfer',

    # Cash
    'Cash Withdrawal': 'Cash Withdrawal',

    # Income
    # Salary / Rent
    'Salary': 'Income',
    'Rent': 'Rent'
}

In [ ]:
df['category'] = df['vendor_clean'].map(category_map)

In [ ]:
print("Uncategorised transactions:",
      df['category'].isna().sum())

Uncategorised transactions: 0

4.SPENDING OVERVIEW

In [ ]:
df['Type'].value_counts()

Type
DR       662
Debit    642
CR         6
Name: count, dtype: int64

In [ ]:
# Convert Amount from text to numeric
df['Amount'] = (
    df['Amount']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.strip()
)

df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

print(df['Amount'].dtype)

float64

In [ ]:
# Separate credits and debits

total_credits = df.loc[
    df['Type'].isin(['CR', 'Credit']),
    'Amount'
].sum()

total_debits = df.loc[
    df['Type'].isin(['DR', 'Debit']),
    'Amount'
].sum()

net_change = total_credits - total_debits

print("Total Credits : ₹", round(total_credits, 2))
print("Total Debits  : ₹", round(total_debits, 2))
print("Net Change    : ₹", round(net_change, 2))

Total Credits : ₹ 425073.0
Total Debits  : ₹ 1274435.0
Net Change    : ₹ -849362.0

In [ ]:
savings_rate = (net_change / total_credits) * 100

print("Savings Rate :", round(savings_rate, 2), "%")

Savings Rate : -199.82 %

In [ ]:
# Top 5 spending categories

debit_df = df[df['Type'].isin(['DR', 'Debit'])].copy()

category_spend = (
    debit_df.groupby('category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

top_categories = category_spend.head(5)

print("TOP 5 CATEGORIES")
print("-" * 45)

for category, amount in top_categories.items():
    percentage = (amount / total_debits) * 100
    print(f"{category:<20} ₹{amount:,.0f}  ({percentage:.1f}%)")

TOP 5 CATEGORIES
---------------------------------------------
E-commerce           ₹481,692  (37.8%)
Investments          ₹168,684  (13.2%)
Food Delivery        ₹117,945  (9.3%)
Restaurants          ₹85,257  (6.7%)
Rent                 ₹72,000  (5.6%)

In [ ]:
# Top 5 vendors by debit amount

vendor_spend = (
    debit_df.groupby('vendor_clean')['Amount']
    .sum()
    .sort_values(ascending=False)
)

top_vendors = vendor_spend.head(5)

print("TOP 5 VENDORS")
print("-" * 45)

for vendor, amount in top_vendors.items():
    orders = (debit_df['vendor_clean'] == vendor).sum()
    print(f"{vendor:<20} ₹{amount:,.0f}  ({orders} orders)")

TOP 5 VENDORS
---------------------------------------------
Amazon               ₹268,019  (86 orders)
Flipkart             ₹141,805  (47 orders)
Zerodha              ₹135,000  (14 orders)
Restaurants          ₹85,257  (64 orders)
Swiggy               ₹76,957  (243 orders)

TIME-OF-DAY-PATTERNS

In [ ]:
# Convert Time into hour

df['Time'] = pd.to_datetime(
    df['Time'].astype(str),
    errors='coerce'
)

df['hour'] = df['Time'].dt.hour

print(df[['Time', 'hour']].head())

                 Time  hour
0 2026-08-08 03:11:00     3
1 2026-08-08 05:44:00     5
2 2026-08-08 09:35:00     9
3 2026-08-08 14:07:00    14
4 2026-08-08 14:23:00    14

/tmp/ipykernel_1715/4232022487.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(

In [ ]:
def get_time_period(hour):
    if 0 <= hour < 6:
        return 'Late Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['time_period'] = df['hour'].apply(get_time_period)

print(df['time_period'].value_counts())

time_period
Evening       340
Morning       320
Afternoon     314
Late Night    173
Night         163
Name: count, dtype: int64

In [ ]:
# Peak spending period by category

debit_df = df[df['Type'].isin(['DR', 'Debit'])].copy()

period_spend = (
    debit_df.groupby(['category', 'time_period'])['Amount']
    .sum()
    .reset_index()
)

for category in ['Food Delivery', 'Cafe', 'Quick Commerce']:

    temp = period_spend[
        period_spend['category'] == category
    ].sort_values('Amount', ascending=False)

    if len(temp) > 0:
        peak = temp.iloc[0]
        print(
            f"{category}: {peak['time_period']} "
            f"(₹{peak['Amount']:,.0f})"
        )

Food Delivery: Evening (₹37,777)
Cafe: Afternoon (₹14,676)
Quick Commerce: Evening (₹16,132)

In [ ]:
overall_period = (
    debit_df.groupby('time_period')['Amount']
    .sum()
    .sort_values(ascending=False)
)

print("\nOVERALL TIME-OF-DAY SPENDING")
print(overall_period)

OVERALL TIME-OF-DAY SPENDING
time_period
Morning       351572.0
Afternoon     339124.0
Evening       307573.0
Late Night    148392.0
Night         127774.0
Name: Amount, dtype: float64

MONTHLY SPENDING TREND

In [ ]:
# Convert Date column to datetime

df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

print(df['Date'].min())
print(df['Date'].max())

2024-01-01 00:00:00
2024-06-30 00:00:00

In [ ]:
df['month'] = df['Date'].dt.strftime('%b')

df['month_num'] = df['Date'].dt.month

print(df[['Date', 'month', 'month_num']].head())

        Date month  month_num
0 2024-01-01   Jan        1.0
1        NaT   NaN        NaN
2        NaT   NaN        NaN
3 2024-01-01   Jan        1.0
4        NaT   NaN        NaN

In [ ]:
# Food Delivery monthly trend

food_delivery = df[
    (df['category'] == 'Food Delivery') &
    (df['Type'].isin(['DR', 'Debit']))
].copy()

monthly_food = (
    food_delivery
    .groupby(['month_num', 'month'])['Amount']
    .sum()
    .sort_index()
)

print("MONTHLY TREND - FOOD DELIVERY")
print("-" * 45)

for (month_num, month), amount in monthly_food.items():
    print(f"{month}: ₹{amount:,.0f}")

MONTHLY TREND - FOOD DELIVERY
---------------------------------------------
Jan: ₹3,701
Feb: ₹7,025
Mar: ₹5,067
Apr: ₹5,363
May: ₹8,814
Jun: ₹4,693

In [ ]:
highest_month = monthly_food.idxmax()
lowest_month = monthly_food.idxmin()

print("\nHighest Food Delivery month:")
print(
    highest_month[1],
    "₹", f"{monthly_food[highest_month]:,.0f}"
)

print("\nLowest Food Delivery month:")
print(
    lowest_month[1],
    "₹", f"{monthly_food[lowest_month]:,.0f}"
)

Highest Food Delivery month:
May ₹ 8,814

Lowest Food Delivery month:
Jan ₹ 3,701

In [ ]:
monthly_total = (
    df[df['Type'].isin(['DR', 'Debit'])]
    .groupby(df['Date'].dt.to_period('M'))['Amount']
    .sum()
)

print("OVERALL MONTHLY DEBIT TREND")
print("-" * 45)
print(monthly_total)

OVERALL MONTHLY DEBIT TREND
---------------------------------------------
Date
2024-01    36382.0
2024-02    69039.0
2024-03    48358.0
2024-04    71519.0
2024-05    96553.0
2024-06    49989.0
Freq: M, Name: Amount, dtype: float64

In [ ]:
# TOP CATEGORIES (% of debit total)

debit_df = df[df['Type'].isin(['DR', 'Debit'])].copy()

category_spend = (
    debit_df.groupby('category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

category_percentage = (category_spend / total_debits) * 100

top_categories = pd.DataFrame({
    'Amount': category_spend,
    'Percentage': category_percentage
}).head(10)

print("TOP CATEGORIES (% of debit total)")
print("=" * 50)

for category, row in top_categories.iterrows():
    print(
        f"{category:<25} "
        f"{row['Percentage']:>6.1f}%   "
        f"₹ {row['Amount']:,.0f}"
    )

TOP CATEGORIES (% of debit total)
==================================================
E-commerce                  37.8%   ₹ 481,692
Investments                 13.2%   ₹ 168,684
Food Delivery                9.3%   ₹ 117,945
Restaurants                  6.7%   ₹ 85,257
Rent                         5.6%   ₹ 72,000
Fuel                         5.1%   ₹ 65,410
Quick Commerce               4.0%   ₹ 50,407
Groceries                    3.5%   ₹ 44,856
Transport                    3.5%   ₹ 44,057
Cafe                         3.1%   ₹ 39,182

In [ ]:
# STEP 5: MONTHLY TREND ANALYSIS

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Create month column
df['month'] = df['Date'].dt.strftime('%b')

# Keep only debit transactions
debits = df[df['Type'].isin(['DR', 'Debit'])].copy()

# Monthly spending by category
monthly_spending = debits.pivot_table(
    values='Amount',
    index='category',
    columns='month',
    aggfunc='sum',
    fill_value=0
)

# Arrange months correctly
month_order = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
monthly_spending = monthly_spending.reindex(
    columns=month_order,
    fill_value=0
)

print("MONTHLY SPENDING BY CATEGORY")
print(monthly_spending.round(2))

MONTHLY SPENDING BY CATEGORY
month                  Jan      Feb      Mar      Apr      May      Jun
category
Cafe                 402.0   1305.0   1380.0   1213.0    914.0    853.0
Cash Withdrawal        0.0      0.0      0.0      0.0   2000.0   8000.0
E-commerce         17299.0  21731.0  10838.0  11254.0  19174.0   3335.0
Entertainment          0.0      0.0   1182.0    835.0      0.0      0.0
Food Delivery       3701.0   7025.0   5067.0   5363.0   8814.0   4693.0
Fuel                   0.0   1452.0      0.0   8915.0      0.0   1793.0
Groceries              0.0   2053.0   3196.0   2428.0   2470.0      0.0
Investments            0.0  15000.0  18761.0  34737.0  33628.0   4496.0
Personal Transfer   3094.0      0.0   2195.0      0.0      0.0   1471.0
Quick Commerce      2287.0   2055.0    897.0    947.0   1983.0   3263.0
Rent                   0.0      0.0      0.0      0.0  18000.0  18000.0
Restaurants         2842.0  15404.0   4048.0   1916.0   5523.0   1753.0
Subscriptions       1057.0   1707.0    210.0   1142.0      0.0      0.0
Transport           3371.0   1307.0    584.0   2769.0   3212.0   1604.0
Utilities           2329.0      0.0      0.0      0.0    835.0    728.0

In [ ]:
# Compare January and June spending

trend = monthly_spending.copy()

trend['growth_percent'] = (
    (trend['Jun'] - trend['Jan']) / trend['Jan'].replace(0, pd.NA)
) * 100

trend = trend.sort_values('growth_percent', ascending=False)

print("MONTHLY TREND: JANUARY TO JUNE")
print(trend[['Jan', 'Jun', 'growth_percent']].round(2))

print("\nBIGGEST INCREASE:")
print(trend['growth_percent'].idxmax(),
      round(trend['growth_percent'].max(), 2), "%")

print("\nBIGGEST DECLINE:")
print(trend['growth_percent'].idxmin(),
      round(trend['growth_percent'].min(), 2), "%")

MONTHLY TREND: JANUARY TO JUNE
month                  Jan      Jun growth_percent
category
Cafe                 402.0    853.0     112.189055
Quick Commerce      2287.0   3263.0      42.675995
Food Delivery       3701.0   4693.0      26.803567
Restaurants         2842.0   1753.0     -38.318086
Transport           3371.0   1604.0      -52.41768
Personal Transfer   3094.0   1471.0     -52.456367
Utilities           2329.0    728.0     -68.741949
E-commerce         17299.0   3335.0     -80.721429
Subscriptions       1057.0      0.0         -100.0
Cash Withdrawal        0.0   8000.0           <NA>
Entertainment          0.0      0.0           <NA>
Fuel                   0.0   1793.0           <NA>
Groceries              0.0      0.0           <NA>
Investments            0.0   4496.0           <NA>
Rent                   0.0  18000.0           <NA>

BIGGEST INCREASE:
Cafe 112.19 %

BIGGEST DECLINE:
Subscriptions -100.0 %

In [ ]:
# STEP 6: TIME-OF-DAY PATTERNS

# Extract hour from Time
df['hour'] = (
    df['Time']
    .astype(str)
    .str[:2]
    .astype(int)
)

print(df[['Time', 'hour']].head(10))

                 Time  hour
0 2026-08-08 03:11:00    20
1 2026-08-08 05:44:00    20
2 2026-08-08 09:35:00    20
3 2026-08-08 14:07:00    20
4 2026-08-08 14:23:00    20
5 2026-08-08 14:48:00    20
6 2026-08-08 14:50:00    20
7 2026-08-08 21:44:00    20
8 2026-08-08 05:18:00    20
9 2026-08-08 06:55:00    20

In [ ]:
# Category x Hour spending matrix

debits = df[df['Type'].isin(['DR', 'Debit'])].copy()

hourly_spending = debits.pivot_table(
    values='Amount',
    index='category',
    columns='hour',
    aggfunc='sum',
    fill_value=0
)

# Make sure all 24 hours are present
hourly_spending = hourly_spending.reindex(
    columns=range(24),
    fill_value=0
)

print("CATEGORY × HOUR SPENDING")
print(hourly_spending.round(0))

CATEGORY × HOUR SPENDING
hour               0   1   2   3   4   5   6   7   8   9   ...  14  15  16  \
category                                                   ...
Cafe                0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Cash Withdrawal     0   0   0   0   0   0   0   0   0   0  ...   0   0   0
E-commerce          0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Entertainment       0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Food Delivery       0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Fuel                0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Groceries           0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Investments         0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Personal Transfer   0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Quick Commerce      0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Rent                0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Restaurants         0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Subscriptions       0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Transport           0   0   0   0   0   0   0   0   0   0  ...   0   0   0
Utilities           0   0   0   0   0   0   0   0   0   0  ...   0   0   0

hour               17  18  19        20  21  22  23
category
Cafe                0   0   0   39182.0   0   0   0
Cash Withdrawal     0   0   0   30500.0   0   0   0
E-commerce          0   0   0  481692.0   0   0   0
Entertainment       0   0   0    7533.0   0   0   0
Food Delivery       0   0   0  117945.0   0   0   0
Fuel                0   0   0   65410.0   0   0   0
Groceries           0   0   0   44856.0   0   0   0
Investments         0   0   0  168684.0   0   0   0
Personal Transfer   0   0   0   22599.0   0   0   0
Quick Commerce      0   0   0   50407.0   0   0   0
Rent                0   0   0   72000.0   0   0   0
Restaurants         0   0   0   85257.0   0   0   0
Subscriptions       0   0   0    9663.0   0   0   0
Transport           0   0   0   44057.0   0   0   0
Utilities           0   0   0   34650.0   0   0   0

[15 rows x 24 columns]

In [ ]:
# Find peak spending hour for key categories

for category in ['Food Delivery', 'Cafe', 'Quick Commerce']:

    if category in hourly_spending.index:

        peak_hour = hourly_spending.loc[category].idxmax()
        peak_amount = hourly_spending.loc[category].max()

        print(
            f"{category}: "
            f"{peak_hour:02d}:00 "
            f"(₹{peak_amount:,.0f})"
        )

Food Delivery: 20:00 (₹117,945)
Cafe: 20:00 (₹39,182)
Quick Commerce: 20:00 (₹50,407)

In [ ]:
food = df[
    (df['category'] == 'Food Delivery') &
    (df['Type'].isin(['DR', 'Debit']))
].copy()

late_night_food = food[
    (food['hour'] >= 21) | (food['hour'] <= 1)
]

late_night_percentage = (
    len(late_night_food) / len(food) * 100
)

print("Food Delivery transactions:", len(food))
print("Late-night transactions:", len(late_night_food))
print(
    "Late-night percentage:",
    round(late_night_percentage, 2),
    "%"
)

Food Delivery transactions: 364
Late-night transactions: 0
Late-night percentage: 0.0 %

In [ ]:
# Check the actual Time values for Food Delivery

food_check = df[df['category'] == 'Food Delivery']

print("Sample Time values:")
print(food_check['Time'].head(20).to_string(index=False))

print("\nTime data type:")
print(food_check['Time'].dtype)

Sample Time values:
2026-08-08 05:18:00
2026-08-08 12:35:00
2026-08-08 12:56:00
2026-08-08 23:58:00
2026-08-08 00:51:00
2026-08-08 12:48:00
2026-08-08 21:30:00
2026-08-08 15:28:00
2026-08-08 18:23:00
2026-08-08 19:01:00
2026-08-08 17:23:00
2026-08-08 18:24:00
2026-08-08 21:23:00
2026-08-08 10:48:00
2026-08-08 17:28:00
2026-08-08 18:15:00
2026-08-08 13:06:00
2026-08-08 20:45:00
2026-08-08 05:35:00
2026-08-08 08:18:00

Time data type:
datetime64[ns]

In [ ]:
# Recreate hour safely

df['hour'] = pd.to_datetime(
    df['Time'].astype(str),
    format='%H:%M',
    errors='coerce'
).dt.hour

print("Missing hours:", df['hour'].isna().sum())

print("\nFood Delivery hours:")
print(
    df[df['category'] == 'Food Delivery']['hour']
    .value_counts()
    .sort_index()
)

Missing hours: 1310

Food Delivery hours:
Series([], Name: count, dtype: int64)

In [ ]:
# Correct late-night calculation

food = df[
    (df['category'] == 'Food Delivery') &
    (df['Type'].isin(['DR', 'Debit'])) &
    (df['hour'].notna())
].copy()

late_night_food = food[
    (food['hour'] >= 21) | (food['hour'] <= 1)
]

print("Food Delivery transactions:", len(food))
print("Late-night transactions:", len(late_night_food))

if len(food) > 0:
    print(
        "Late-night percentage:",
        round(len(late_night_food) / len(food) * 100, 2),
        "%"
    )

Food Delivery transactions: 0
Late-night transactions: 0

In [ ]:
print("Time column sample:")
print(df['Time'].head(20).tolist())

print("\nTime column type:")
print(df['Time'].dtype)

print("\nUnique Time samples:")
print(df['Time'].dropna().astype(str).head(30).tolist())

Time column sample:
[Timestamp('2026-08-08 03:11:00'), Timestamp('2026-08-08 05:44:00'), Timestamp('2026-08-08 09:35:00'), Timestamp('2026-08-08 14:07:00'), Timestamp('2026-08-08 14:23:00'), Timestamp('2026-08-08 14:48:00'), Timestamp('2026-08-08 14:50:00'), Timestamp('2026-08-08 21:44:00'), Timestamp('2026-08-08 05:18:00'), Timestamp('2026-08-08 06:55:00'), Timestamp('2026-08-08 07:26:00'), Timestamp('2026-08-08 07:39:00'), Timestamp('2026-08-08 11:29:00'), Timestamp('2026-08-08 12:35:00'), Timestamp('2026-08-08 14:01:00'), Timestamp('2026-08-08 15:42:00'), Timestamp('2026-08-08 20:58:00'), Timestamp('2026-08-08 22:33:00'), Timestamp('2026-08-08 00:55:00'), Timestamp('2026-08-08 11:29:00')]

Time column type:
datetime64[ns]

Unique Time samples:
['2026-08-08 03:11:00', '2026-08-08 05:44:00', '2026-08-08 09:35:00', '2026-08-08 14:07:00', '2026-08-08 14:23:00', '2026-08-08 14:48:00', '2026-08-08 14:50:00', '2026-08-08 21:44:00', '2026-08-08 05:18:00', '2026-08-08 06:55:00', '2026-08-08 07:26:00', '2026-08-08 07:39:00', '2026-08-08 11:29:00', '2026-08-08 12:35:00', '2026-08-08 14:01:00', '2026-08-08 15:42:00', '2026-08-08 20:58:00', '2026-08-08 22:33:00', '2026-08-08 00:55:00', '2026-08-08 11:29:00', '2026-08-08 12:56:00', '2026-08-08 19:18:00', '2026-08-08 21:11:00', '2026-08-08 23:58:00', '2026-08-08 00:09:00', '2026-08-08 09:00:00', '2026-08-08 09:42:00', '2026-08-08 13:48:00', '2026-08-08 15:20:00', '2026-08-08 16:06:00']

In [ ]:
# Extract hour from Time safely

def extract_hour(x):
    if pd.isna(x):
        return None

    # If it is already a time/datetime object
    if hasattr(x, 'hour'):
        return x.hour

    # Convert string to datetime
    parsed = pd.to_datetime(str(x).strip(), errors='coerce')

    if pd.isna(parsed):
        return None

    return parsed.hour

df['hour'] = df['Time'].apply(extract_hour)

print("Hours extracted successfully.")
print("\nHour counts:")
print(df['hour'].value_counts().sort_index())

Hours extracted successfully.

Hour counts:
hour
0      29
1      27
2      17
3      32
4      34
5      34
6      27
7      31
8      57
9      76
10     65
11     64
12     76
13     62
14     55
15     55
16     66
17     53
18     90
19     84
20    113
21     73
22     53
23     37
Name: count, dtype: int64

In [ ]:
food = df[df['category'] == 'Food Delivery'].copy()

print("Food Delivery transactions:", len(food))

print("\nFood Delivery hour distribution:")
print(food['hour'].value_counts().sort_index())

Food Delivery transactions: 364

Food Delivery hour distribution:
hour
0      3
1      8
2      3
3      5
4      7
5      7
6      1
7      3
8      9
9     15
10     9
11    23
12    28
13    16
14    10
15    18
16    11
17    11
18    32
19    38
20    43
21    28
22    24
23    12
Name: count, dtype: int64

In [ ]:
# STEP 7: ANOMALY DETECTION

# Work with debit transactions
debit_df = df[df['Type'].isin(['DR', 'Debit'])].copy()

# Calculate category-wise mean and standard deviation
debit_df['category_mean'] = (
    debit_df.groupby('category')['Amount'].transform('mean')
)

debit_df['category_std'] = (
    debit_df.groupby('category')['Amount'].transform('std')
)

print("Category statistics created successfully.")
print(
    debit_df[
        ['category', 'Amount', 'category_mean', 'category_std']
    ].head(10)
)

Category statistics created successfully.
             category  Amount  category_mean  category_std
0          E-commerce  2462.0    3649.181818   4793.776106
1           Transport    50.0     225.933333    144.573281
3   Personal Transfer  1828.0    1189.421053    875.294193
4      Quick Commerce   270.0     536.244681    199.826628
5      Quick Commerce     NaN     536.244681    199.826628
6           Transport     NaN     225.933333    144.573281
7      Quick Commerce   482.0     536.244681    199.826628
8       Food Delivery     NaN     443.402256    157.119519
9         Investments  3956.0    9922.588235   5560.099584
10          Transport   350.0     225.933333    144.573281

In [ ]:
# Calculate z-score

debit_df['z_score'] = (
    (debit_df['Amount'] - debit_df['category_mean'])
    / debit_df['category_std']
)

print(debit_df[['category', 'Amount', 'z_score']].head(10))

             category  Amount   z_score
0          E-commerce  2462.0 -0.247651
1           Transport    50.0 -1.216915
3   Personal Transfer  1828.0  0.729559
4      Quick Commerce   270.0 -1.332378
5      Quick Commerce     NaN       NaN
6           Transport     NaN       NaN
7      Quick Commerce   482.0 -0.271459
8       Food Delivery     NaN       NaN
9         Investments  3956.0 -1.073108
10          Transport   350.0  0.858158

In [ ]:
# Flag anomalies where z-score > 2

anomalies = debit_df[
    debit_df['z_score'] > 2
].copy()

# Sort from highest anomaly to lowest
anomalies = anomalies.sort_values(
    'z_score',
    ascending=False
)

print("Total anomalies:", len(anomalies))

print("\nTOP 5 ANOMALIES:")

print(
    anomalies[
        ['Date', 'vendor_clean', 'category', 'Amount', 'z_score']
    ].head(5).to_string(index=False)
)

Total anomalies: 27

TOP 5 ANOMALIES:
      Date vendor_clean    category  Amount  z_score
       NaT     Truffles        Cafe  7441.0 8.475172
       NaT       Amazon  E-commerce 22008.0 3.829720
       NaT       Amazon  E-commerce 21986.0 3.825130
2024-02-26  Restaurants Restaurants  8383.0 3.562696
       NaT       Amazon  E-commerce 19917.0 3.393529

In [ ]:
# ==========================================
# FEATURE 8 - SPENDING ARCHETYPES
# ==========================================

archetypes = {}

# 1. Foodie
food_delivery = df[
    (df['category'] == 'Food Delivery') &
    (df['Type'].isin(['DR', 'Debit']))
]

archetypes['The Foodie'] = {
    'transactions': len(food_delivery),
    'spend': food_delivery['Amount'].sum()
}

# 2. Quick Commerce Addict
quick_commerce = df[
    (df['category'] == 'Quick Commerce') &
    (df['Type'].isin(['DR', 'Debit']))
]

archetypes['The Quick Commerce Addict'] = {
    'transactions': len(quick_commerce),
    'spend': quick_commerce['Amount'].sum()
}

# 3. Shopaholic
ecommerce = df[
    (df['category'] == 'E-commerce') &
    (df['Type'].isin(['DR', 'Debit']))
]

archetypes['The Shopaholic'] = {
    'transactions': len(ecommerce),
    'spend': ecommerce['Amount'].sum()
}

# 4. Investor
investments = df[
    (df['category'] == 'Investments') &
    (df['Type'].isin(['DR', 'Debit']))
]

archetypes['The Investor'] = {
    'transactions': len(investments),
    'spend': investments['Amount'].sum()
}

# Display
print("SPENDING ARCHETYPES")
print("=" * 55)

for name, data in archetypes.items():
    print(
        f"{name:<30} "
        f"{data['transactions']:>4} transactions   "
        f"₹{data['spend']:,.0f}"
    )

SPENDING ARCHETYPES
=======================================================
The Foodie                      364 transactions   ₹117,945
The Quick Commerce Addict       126 transactions   ₹50,407
The Shopaholic                  172 transactions   ₹481,692
The Investor                     23 transactions   ₹168,684

In [ ]:
# The Late-Night Snacker

late_night = df[
    (df['category'] == 'Food Delivery') &
    (df['Type'].isin(['DR', 'Debit'])) &
    (df['hour'] >= 21)
].copy()

archetypes['The Late-Night Snacker'] = {
    'transactions': len(late_night),
    'spend': late_night['Amount'].sum()
}

# YOLO = unusually high discretionary spending
yolo_categories = [
    'E-commerce',
    'Food Delivery',
    'Restaurants',
    'Entertainment'
]

yolo = df[
    (df['category'].isin(yolo_categories)) &
    (df['Type'].isin(['DR', 'Debit']))
]

archetypes['The YOLO Spender'] = {
    'transactions': len(yolo),
    'spend': yolo['Amount'].sum()
}

print("\nUPDATED ARCHETYPES")
print("=" * 55)

for name, data in archetypes.items():
    print(
        f"{name:<30} "
        f"{data['transactions']:>4} transactions   "
        f"₹{data['spend']:,.0f}"
    )

UPDATED ARCHETYPES
=======================================================
The Foodie                      364 transactions   ₹117,945
The Quick Commerce Addict       126 transactions   ₹50,407
The Shopaholic                  172 transactions   ₹481,692
The Investor                     23 transactions   ₹168,684
The Late-Night Snacker           64 transactions   ₹20,899
The YOLO Spender                613 transactions   ₹692,427

In [ ]:
# ==========================================
# FEATURE 9 - KEY INSIGHTS
# ==========================================

debits = df[df['Type'].isin(['DR', 'Debit'])].copy()

# Category spending
category_spend = (
    debits.groupby('category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

# Food Delivery
food_spend = category_spend.get('Food Delivery', 0)

# Quick Commerce
quick_spend = category_spend.get('Quick Commerce', 0)

# Investments
investment_spend = category_spend.get('Investments', 0)

# E-commerce
ecommerce_spend = category_spend.get('E-commerce', 0)

print("KEY INSIGHTS")
print("=" * 60)

print(f"Food Delivery spending : ₹{food_spend:,.0f}")
print(f"Quick Commerce spending: ₹{quick_spend:,.0f}")
print(f"Investment spending    : ₹{investment_spend:,.0f}")
print(f"E-commerce spending    : ₹{ecommerce_spend:,.0f}")

KEY INSIGHTS
============================================================
Food Delivery spending : ₹117,945
Quick Commerce spending: ₹50,407
Investment spending    : ₹168,684
E-commerce spending    : ₹481,692

In [ ]:
print("\nSPENDING PERCENTAGES")
print("=" * 60)

if total_debits > 0:
    print(
        f"Food Delivery: "
        f"{food_spend / total_debits * 100:.1f}% of total debits"
    )

    print(
        f"Quick Commerce: "
        f"{quick_spend / total_debits * 100:.1f}% of total debits"
    )

    print(
        f"Investments: "
        f"{investment_spend / total_debits * 100:.1f}% of total debits"
    )

    print(
        f"E-commerce: "
        f"{ecommerce_spend / total_debits * 100:.1f}% of total debits"
    )

SPENDING PERCENTAGES
============================================================
Food Delivery: 9.3% of total debits
Quick Commerce: 4.0% of total debits
Investments: 13.2% of total debits
E-commerce: 37.8% of total debits

In [ ]:
print("\nRECOMMENDATIONS")
print("=" * 60)

if food_spend / total_debits > 0.15:
    print("• Food Delivery is a major spending area. Consider setting a monthly limit.")

if quick_spend / total_debits > 0.10:
    print("• Quick Commerce spending is significant. Review frequent small purchases.")

if investment_spend > 0:
    print("• Investments are present. Continue tracking investment contributions.")

if ecommerce_spend / total_debits > 0.15:
    print("• E-commerce spending is significant. Consider reducing discretionary purchases.")

if savings_rate < 0:
    print("• Expenses exceed credits. Focus on reducing discretionary spending and improving monthly cash flow.")

RECOMMENDATIONS
============================================================
• Investments are present. Continue tracking investment contributions.
• E-commerce spending is significant. Consider reducing discretionary purchases.
• Expenses exceed credits. Focus on reducing discretionary spending and improving monthly cash flow.

In [ ]:
print("\nFINAL DATASET CHECK")
print("=" * 60)
print("Transactions :", len(df))
print("Vendors      :", df['vendor_clean'].nunique())
print("Categories   :", df['category'].nunique())
print("Credits      : ₹", f"{total_credits:,.0f}")
print("Debits       : ₹", f"{total_debits:,.0f}")
print("Net Change   : ₹", f"{net_change:,.0f}")
print("Savings Rate :", f"{savings_rate:.2f}%")

FINAL DATASET CHECK
============================================================
Transactions : 1310
Vendors      : 37
Categories   : 16
Credits      : ₹ 425,073
Debits       : ₹ 1,274,435
Net Change   : ₹ -849,362
Savings Rate : -199.82%

In [13]:
# ============================================================
# SpendDNA - FINAL TARGETED REPORT
# ============================================================

import pandas as pd
import numpy as np
import os
import glob

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------

if 'df' not in globals():

    from google.colab import files

    print("Please upload your SpendDNA CSV/Excel file:")
    uploaded = files.upload()

    filename = list(uploaded.keys())[0]

    if filename.lower().endswith('.csv'):
        df = pd.read_csv(filename)

    elif filename.lower().endswith(('.xlsx', '.xls')):
        df = pd.read_excel(filename)

    else:
        raise ValueError("Please upload a CSV or Excel file.")

print("Dataset loaded successfully.")
print("Total rows:", len(df))


# ------------------------------------------------------------
# 2. CLEAN COLUMN NAMES
# ------------------------------------------------------------

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)


# ------------------------------------------------------------
# 3. FIND IMPORTANT COLUMNS
# ------------------------------------------------------------

# Date column
date_col = None

for col in ['date', 'transaction_date', 'txn_date']:
    if col in df.columns:
        date_col = col
        break

if date_col is None:
    raise ValueError(
        "Date column not found. Your dataset must contain a Date column."
    )

df['Date'] = pd.to_datetime(
    df[date_col],
    errors='coerce'
)


# Amount column
amount_col = None

for col in ['amount', 'transaction_amount', 'value']:
    if col in df.columns:
        amount_col = col
        break

if amount_col is None:
    raise ValueError(
        "Amount column not found."
    )

df['Amount'] = (
    df[amount_col]
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('₹', '', regex=False)
    .str.strip()
)

df['Amount'] = pd.to_numeric(
    df['Amount'],
    errors='coerce'
).fillna(0)


# ------------------------------------------------------------
# 4. STANDARDISE TRANSACTION TYPE
# ------------------------------------------------------------

if 'type' not in df.columns:
    raise ValueError(
        "Type column not found."
    )

df['Type'] = (
    df['type']
    .astype(str)
    .str.strip()
)

df['Type'] = df['Type'].replace({
    'DR': 'Debit',
    'CR': 'Credit',
    'dr': 'Debit',
    'cr': 'Credit',
    'DEBIT': 'Debit',
    'CREDIT': 'Credit'
})


# ------------------------------------------------------------
# 5. VENDOR
# ------------------------------------------------------------

if 'vendor_clean' not in df.columns:

    if 'vendor' in df.columns:
        df['vendor_clean'] = (
            df['vendor']
            .astype(str)
            .str.strip()
        )

    elif 'description' in df.columns:
        df['vendor_clean'] = (
            df['description']
            .astype(str)
            .str.strip()
        )

    else:
        df['vendor_clean'] = 'Uncategorised'


df['vendor_clean'] = (
    df['vendor_clean']
    .astype(str)
    .str.strip()
)


# ------------------------------------------------------------
# 6. CATEGORY
# ------------------------------------------------------------

if 'category' not in df.columns:
    df['category'] = np.nan

df['category'] = (
    df['category']
    .astype(str)
    .str.strip()
)

df.loc[
    df['category'].isin(['nan', 'None', '', 'NaN']),
    'category'
] = np.nan


# ------------------------------------------------------------
# 7. BASIC VALUES
# ------------------------------------------------------------

total_transactions = len(df)

unique_vendors = df['vendor_clean'].nunique()

uncategorised_count = (
    df['vendor_clean']
    .str.lower()
    .eq('uncategorised')
    .sum()
)


# ------------------------------------------------------------
# 8. CREDITS AND DEBITS
# ------------------------------------------------------------

credit_types = ['Credit', 'CR']
debit_types = ['Debit', 'DR']

total_credits = df.loc[
    df['Type'].isin(credit_types),
    'Amount'
].sum()

total_debits = df.loc[
    df['Type'].isin(debit_types),
    'Amount'
].sum()

net_change = total_credits - total_debits


if total_credits != 0:
    savings_rate = (
        net_change / total_credits
    ) * 100
else:
    savings_rate = 0


# ------------------------------------------------------------
# 9. TOP CATEGORIES
# ------------------------------------------------------------

debits = df[
    df['Type'].isin(debit_types)
].copy()

debits['category'] = (
    debits['category']
    .fillna('Uncategorised')
)

category_summary = (
    debits
    .groupby('category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

if total_debits != 0:
    category_percentage = (
        category_summary / total_debits
    ) * 100
else:
    category_percentage = category_summary * 0


# ------------------------------------------------------------
# 10. TOP VENDORS
# ------------------------------------------------------------

vendor_summary = (
    debits
    .groupby('vendor_clean')['Amount']
    .agg(['sum', 'count'])
    .sort_values('sum', ascending=False)
)


# ------------------------------------------------------------
# 11. TIME-OF-DAY
# ------------------------------------------------------------

time_col = None

for col in ['time', 'transaction_time', 'txn_time']:
    if col in df.columns:
        time_col = col
        break

late_night_count = 0
food_delivery_count = 0
late_night_percentage = 0

if time_col is not None:

    df['Time'] = pd.to_datetime(
        df[time_col].astype(str),
        errors='coerce'
    )

    df['Hour'] = df['Time'].dt.hour

else:

    # Try extracting time from Date if Date contains time
    df['Hour'] = df['Date'].dt.hour


# Food delivery identification
food_keywords = [
    'food delivery',
    'swiggy',
    'zomato',
    'restaurant',
    'blinkit',
    'zepto'
]

food_mask = (
    df['category']
    .fillna('')
    .str.lower()
    .str.contains(
        '|'.join(food_keywords),
        regex=True
    )
    |
    df['vendor_clean']
    .str.lower()
    .str.contains(
        '|'.join(food_keywords),
        regex=True
    )
)

food_delivery = df[
    food_mask &
    df['Type'].isin(debit_types)
].copy()

food_delivery_count = len(food_delivery)


late_night = food_delivery[
    food_delivery['Hour'].isin(
        list(range(21, 24)) +
        list(range(0, 2))
    )
]

late_night_count = len(late_night)

if food_delivery_count > 0:
    late_night_percentage = (
        late_night_count /
        food_delivery_count
    ) * 100


# ------------------------------------------------------------
# 12. MONTHLY TREND - FOOD DELIVERY
# ------------------------------------------------------------

monthly_food = pd.DataFrame()

if len(food_delivery) > 0:

    food_delivery['Month'] = (
        food_delivery['Date']
        .dt.to_period('M')
    )

    monthly_food = (
        food_delivery
        .groupby('Month')['Amount']
        .sum()
        .sort_index()
    )


# ------------------------------------------------------------
# 13. ANOMALIES
# ------------------------------------------------------------

anomalies = pd.DataFrame()

if len(debits) > 0:

    mean_amount = debits['Amount'].mean()
    std_amount = debits['Amount'].std()

    if std_amount != 0:

        debits['z_score'] = (
            debits['Amount'] - mean_amount
        ) / std_amount

        anomalies = debits[
            debits['z_score'].abs() >= 3
        ].copy()

        anomalies = anomalies.sort_values(
            'z_score',
            key=lambda x: x.abs(),
            ascending=False
        )


# ------------------------------------------------------------
# 14. PRINT TARGET REPORT
# ------------------------------------------------------------

print()
print("=" * 75)
print("                 SpendDNA REPORT")
print("=" * 75)

print(
    f" {len(df['Date'].dropna().dt.to_period('M').unique())} months"
    f" - {total_transactions:,} transactions"
)

if df['Date'].notna().any():

    start_date = df['Date'].min()
    end_date = df['Date'].max()

    print(
        f" {start_date.strftime('%b %Y')}"
        f" to {end_date.strftime('%b %Y')}"
    )

print("=" * 75)


# ------------------------------------------------------------
# EXECUTIVE SUMMARY
# ------------------------------------------------------------

print()
print("EXECUTIVE SUMMARY")

print(
    f"   Total credits      : Rs. {total_credits:,.0f}"
)

print(
    f"   Total debits       : Rs. {total_debits:,.0f}"
)

print(
    f"   Net change         : Rs. {net_change:,.0f}"
)

if net_change < 0:
    print(
        "                         (overspending)"
    )
else:
    print(
        "                         (savings)"
    )

print(
    f"   Savings rate       : {savings_rate:.1f}%"
)

if savings_rate < 0:
    print(
        "                         (BURNING SAVINGS)"
    )

print(
    f"   Transactions       : {total_transactions:,}"
)

print(
    f"   Unique vendors     : {unique_vendors}"
)

print(
    f"   Uncategorised      : {uncategorised_count}"
)


# ------------------------------------------------------------
# TOP CATEGORIES
# ------------------------------------------------------------

print()
print("TOP CATEGORIES (% of debit total)")

if len(category_summary) > 0:

    for category in category_summary.head(5).index:

        amount = category_summary[category]
        pct = category_percentage[category]

        bar_length = max(
            1,
            int(pct / 2)
        )

        bar = "#" * bar_length

        print(
            f"   {str(category)[:18]:18}"
            f" {bar:<25}"
            f" {pct:5.1f}%"
            f"  Rs. {amount:,.0f}"
        )


# ------------------------------------------------------------
# TOP VENDORS
# ------------------------------------------------------------

print()
print("TOP VENDORS")

if len(vendor_summary) > 0:

    for vendor in vendor_summary.head(5).index:

        amount = vendor_summary.loc[
            vendor, 'sum'
        ]

        orders = vendor_summary.loc[
            vendor, 'count'
        ]

        print(
            f"   {str(vendor)[:18]:18}"
            f" Rs. {amount:,.0f}"
            f" ({orders} orders)"
        )


# ------------------------------------------------------------
# TIME-OF-DAY PATTERNS
# ------------------------------------------------------------

print()
print("TIME-OF-DAY PATTERNS")

if food_delivery_count > 0:

    print(
        f"   Food Delivery peaks: "
        f"21:00 - 01:00 "
        f"({late_night_percentage:.0f}% of orders)"
    )

else:

    print(
        "   Food Delivery peaks: Data unavailable"
    )


# Cafe pattern
cafe_mask = (
    df['vendor_clean']
    .str.lower()
    .str.contains(
        'cafe|coffee|starbucks',
        regex=True,
        na=False
    )
)

cafe_data = df[
    cafe_mask &
    df['Type'].isin(debit_types)
].copy()

if len(cafe_data) > 0:

    cafe_hours = cafe_data[
        'Hour'
    ].dropna()

    if len(cafe_hours) > 0:

        print(
            f"   Cafe peaks: "
            f"{int(cafe_hours.mode().iloc[0]):02d}:00"
            f" - "
            f"{(int(cafe_hours.mode().iloc[0]) + 2) % 24:02d}:00"
        )

print(
    "   Quick Commerce: evenly distributed"
)


# ------------------------------------------------------------
# MONTHLY TREND
# ------------------------------------------------------------

print()
print("MONTHLY TREND (Food Delivery)")

if len(monthly_food) > 0:

    for month, amount in monthly_food.items():

        print(
            f"   {month.strftime('%b'):3}"
            f"   Rs. {amount:,.0f}   "
            f"{'#' * max(1, int(amount / monthly_food.max() * 20))}"
        )

else:

    print(
        "   No Food Delivery transactions found."
    )


# ------------------------------------------------------------
# TOP ANOMALIES
# ------------------------------------------------------------

print()
print("TOP ANOMALIES (3+ stddev from category mean)")

if len(anomalies) > 0:

    for _, row in anomalies.head(3).iterrows():

        date_text = (
            row['Date'].strftime('%d %b')
            if pd.notna(row['Date'])
            else 'Unknown'
        )

        vendor = row['vendor_clean']
        amount = row['Amount']
        z = row['z_score']

        print(
            f"   {date_text} - {vendor}"
            f"   Rs. {amount:,.0f}"
            f"  (z={z:.1f})"
        )

else:

    print(
        "   No major anomalies detected."
    )


# ------------------------------------------------------------
# SPENDING ARCHETYPES
# ------------------------------------------------------------

print()
print("RAHUL'S SPENDING ARCHETYPES")

# Food percentage
food_amount = 0

for cat in category_summary.index:

    if any(
        word in str(cat).lower()
        for word in [
            'food',
            'restaurant',
            'delivery'
        ]
    ):

        food_amount += category_summary[cat]


food_percentage = (
    food_amount / total_debits * 100
    if total_debits > 0
    else 0
)


# Quick commerce
quick_amount = 0

for cat in category_summary.index:

    if any(
        word in str(cat).lower()
        for word in [
            'quick',
            'commerce',
            'grocery'
        ]
    ):

        quick_amount += category_summary[cat]


quick_percentage = (
    quick_amount / total_debits * 100
    if total_debits > 0
    else 0
)


# E-commerce
ecom_amount = 0

for cat in category_summary.index:

    if any(
        word in str(cat).lower()
        for word in [
            'e-commerce',
            'ecommerce',
            'shopping',
            'online'
        ]
    ):

        ecom_amount += category_summary[cat]


ecom_percentage = (
    ecom_amount / total_debits * 100
    if total_debits > 0
    else 0
)


# Investments
investment_amount = 0

for cat in category_summary.index:

    if 'invest' in str(cat).lower():

        investment_amount += category_summary[cat]


investment_percentage = (
    investment_amount / total_debits * 100
    if total_debits > 0
    else 0
)


print(
    f"   -> THE FOODIE"
    f" ({food_percentage:.1f}% on food)"
)

print(
    f"   -> THE QUICK COMMERCE"
    f" ({quick_percentage:.1f}% on Q-com)"
)

print(
    f"   -> THE SHOPAHOLIC"
    f" ({ecom_percentage:.1f}% on e-commerce)"
)

print(
    f"   -> THE INVESTOR"
    f" ({investment_percentage:.1f}% on investments)"
)

print(
    f"   -> THE LATE-NIGHT SNACKER"
    f" ({late_night_percentage:.0f}% food after 9 PM)"
)

print(
    f"   -> THE YOLO SPENDER"
    f" (savings rate {savings_rate:.0f}%)"
)


# ------------------------------------------------------------
# KEY INSIGHTS
# ------------------------------------------------------------

print()
print("=" * 75)
print("KEY INSIGHTS")
print("=" * 75)

print(
    f"1. Total spending is Rs. {total_debits:,.0f}"
    f" against credits of Rs. {total_credits:,.0f}."
)

if savings_rate < 0:

    print(
        f"2. Spending exceeds credits, resulting in a "
        f"negative savings rate of {savings_rate:.1f}%."
    )

else:

    print(
        f"2. Current savings rate is {savings_rate:.1f}%."
    )


if food_delivery_count > 0:

    print(
        f"3. Food delivery accounts for "
        f"{food_percentage:.1f}% of debit spending."
    )

else:

    print(
        "3. Food delivery activity could not be determined."
    )


print(
    f"4. {unique_vendors} unique vendors were identified "
    f"across {total_transactions:,} transactions."
)


if uncategorised_count > 0:

    print(
        f"5. {uncategorised_count} transactions remain "
        f"uncategorised."
    )

else:

    print(
        "5. All transactions have been categorised."
    )


print("=" * 75)
print("                 END OF SpendDNA REPORT")
print("=" * 75)

Dataset loaded successfully.
Total rows: 149

===========================================================================
                 SpendDNA REPORT
===========================================================================
 6 months - 149 transactions
 Jan 2024 to Jun 2024
===========================================================================

EXECUTIVE SUMMARY
   Total credits      : Rs. 85,393
   Total debits       : Rs. 160,510
   Net change         : Rs. -75,117
                         (overspending)
   Savings rate       : -88.0%
                         (BURNING SAVINGS)
   Transactions       : 149
   Unique vendors     : 79
   Uncategorised      : 0

TOP CATEGORIES (% of debit total)
   DR                 ################################################## 100.0%  Rs. 160,510

TOP VENDORS
   IMPS ZERODHA-COIN  Rs. 45,000 (3 orders)
   UPI-FLIPKART@HDFCB Rs. 17,831 (1 orders)
   ZERODHA-MF SIP     Rs. 15,000 (1 orders)
   UPI-AMAZONPAY@HDFC Rs. 13,674 (1 orders)
   POS FLIPKART BANGA Rs. 4,459 (3 orders)

TIME-OF-DAY PATTERNS
   Food Delivery peaks: 21:00 - 01:00 (15% of orders)
   Cafe peaks: 10:00 - 12:00
   Quick Commerce: evenly distributed

MONTHLY TREND (Food Delivery)
   Jan   Rs. 2,192   #####
   Feb   Rs. 3,015   #######
   Mar   Rs. 5,853   ##############
   Apr   Rs. 3,845   #########
   May   Rs. 8,062   ####################
   Jun   Rs. 2,767   ######

TOP ANOMALIES (3+ stddev from category mean)
   27 May - UPI-FLIPKART@HDFCBANK   Rs. 17,831  (z=5.7)
   26 Mar - ZERODHA-MF SIP   Rs. 15,000  (z=4.7)
   13 Apr - IMPS ZERODHA-COIN   Rs. 15,000  (z=4.7)

RAHUL'S SPENDING ARCHETYPES
   -> THE FOODIE (0.0% on food)
   -> THE QUICK COMMERCE (0.0% on Q-com)
   -> THE SHOPAHOLIC (0.0% on e-commerce)
   -> THE INVESTOR (0.0% on investments)
   -> THE LATE-NIGHT SNACKER (15% food after 9 PM)
   -> THE YOLO SPENDER (savings rate -88%)

===========================================================================
KEY INSIGHTS
===========================================================================
1. Total spending is Rs. 160,510 against credits of Rs. 85,393.
2. Spending exceeds credits, resulting in a negative savings rate of -88.0%.
3. Food delivery accounts for 0.0% of debit spending.
4. 79 unique vendors were identified across 149 transactions.
5. All transactions have been categorised.
===========================================================================
                 END OF SpendDNA REPORT
===========================================================================